data_ingestion:
  bucket_name: "mybucket1311"
  bucket_file_name: "Hotel_Reservations.csv"
  train_ratio: 0.8

data_processing:
  categorial_cols:
    - type_of_meal_plan
    - required_car_parking_space
    - room_type_reserved
    - market_segment_type
    - repeated_guest
    - booking_status
  numerical_cols:
    - no_of_adults
    - no_of_children
    - lead_time
    - avg_price_per_room
    - no_of_special_requests
    - no_of_weekend_nights
    - no_of_week_nights
    - arrival_year
    - arrival_month
    - arrival_date
    - no_of_previous_cancellations
    - no_of_previous_bookings_not_canceled   
  skewness_thershold: 5
  no_of_features: 10